import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/Components/Header/Header";
import Footer from "@/Components/Footer/Footer";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { AppProvider } from "@/Provider/AppContext";
import { AuthProvider } from "@/Provider/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Food",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
        <main className="max-w-6xl max-lg:max-w-3xl mx-auto p-4">
          <AuthProvider>
            <AppProvider>
              <ToastContainer position="top-right" autoClose={1000} />
              <Header />
              {children}
              <Footer />
            </AppProvider>
          </AuthProvider>
        </main>
      </body>
    </html>
  );
}
